### ISSUE TITLE
Broken minification in if else stanza

### ISSUE THREAD

**Issue by DavidPrevot** [tchwork/jsqueeze#15]
[ Sorry in advance for my pour JavaScript knowledge.]

Hi,

The following stanza from [ace.js](https://github.com/owncloud/files_texteditor/blob/master/js/vendor/ace/src-noconflict/ace.js#L8669) seems to be broken after being minified:

    if ("aaa".split(/a/).length == 0)
        this.$split = function(text) {
            return text.replace(/\r\n|\r/g, "\n").split("\n");
        }
    else
        this.$split = function(text) {
            return text.split(/\r\n|\r|\n/);
        };

Becomes:

    if("aaa".split(/a/).length==0)this.$split=function(e){return e.replace(/\r\n|\r/g,"\n").split("\n")}else this.$split=function(e){return e.split(/\r\n|\r|\n/)};

And causes the browser to choke on the minified JavaScript file.

FWIW, the following (fixed?) code provides a working minified JavaScript file:

    if ("aaa".split(/a/).length == 0) {
        this.$split = function(text) {
            return text.replace(/\r\n|\r/g, "\n").split("\n");
        }
    } else {
        this.$split = function(text) {
            return text.split(/\r\n|\r|\n/);
        };
    }

@AdamWill, I used your [fix](https://github.com/AdamWill/core/commit/da866a885bbc035a12c4e98fd0eed2ec660b0d7f) (thanks BTW) to test OC8 with JSqueeze and ran into this issue (making the whole webui unusable, since all the JavaScript is concatenated in one file), did you find another workaround, or were you simply not affected by this issue?

**Comment by AdamWill** [comment]
Hi David! I was testing a few weeks ago so this may have changed since then. When I tested it mostly seemed to work, OC certainly wasn't unusable. The upstream devs tested harder, though, and said they'd found a couple of things that were broken; I'm volunteered to reproduce those and send a report to JSqueeze, I just haven't had time yet :(

Once I get the initial Fedora OC 8 packages done (with JS minification disabled) then getting  back to this is next on my OC todo list.

**Comment by DavidPrevot** [comment]
> Closed #15 via dc3c4073c2060d62a8578848c5d222a8b7608df1.

Thanks, fix confirmed in the pointed use case.
